### ISSUE TITLE
1.19.2 spectrelib update

### ISSUE THREAD

**Issue by JulzKowalski** [wendall911/BetterDays#6] opened 2023-12-20 08:32 UTC
at com.illusivesoulworks.spectrelib.SpectreClientFabricMod.prepareConfigs(SpectreClientFabricMod.java:57)
	at net.minecraft.class_310.handler$igl001$spectrelib$init(class_310.java:36472)
	at net.minecraft.class_310.<init>(class_310.java:456)

**Comment by Poopooracoocoo** [comment] 2024-01-20 00:30
Duplicate of #4 

Until this is fixed, users can grab https://github.com/illusivesoulworks/spectrelib/releases and put it into their mods folder. Fabric Loader will load the newer version.

**Closed as completed** 2024-03-19 18:05 UTC
